### ISSUE TITLE
Manhattan Graph

### ISSUE THREAD

**Issue by campbellbartlett** [campbellbartlett/live-cricketscores.com#50]
A graph that shows the runs scored / wickets taken each over of an innings.
The bars of the graph look like the 'Manhattan skyline' hence the name

**Comment by karthikrp** [comment]
@campbellbartlett 
I found this repo in some old post in dev.to
Still looking for collaborators?

**Comment by campbellbartlett** [comment]
Hey @karthikrp 
Yes always happy to have new collaborators. I’ll take a look at your PR.
Great to have you on board!

**Comment by campbellbartlett** [comment]
I’m going to close this now that @karthikrp has made the changes. 
I’m interested to see how this looks at the end of a Test Match when there are 4 innings with over 100 overs - if anything looks weird in this situation we can fix forward with a new issue.
